language: java

before_install:
- chmod +x gradlew

deploy:
  provider: heroku
  api_key:
    secure: QfduUnEuXyVMaOKAOh/JTl9mV+RLsEtMCCPV4jbv5lbartPit9jFENFeTkzV2MKlf5gxCIEyiDropi31Yb5XhvIVcQNZn/GfSAWrQqvAoqCqVjhYj6Fu284mV8fyw4RLbxWja5/xFiS4FZHvDo5LHmEyCSYClmrgu6d08COsz+4hGsMhmjYJP8+dPfV4gpJXypO2kPli8MFLLSwSPbhyAe5KEnO0z/y6f9cgDiBVMt7aE/j6NI5nEcKpqFtdvn7Vzrp8Nt/SE/LK7C/I0hrZzRhDL8FJxJ/o0KADtmCD4ygSIpxs2R8sQ0xclQdd73Bkompby3mPbLtw37JvsAQff/qJSEs7Wkmzd3uiOzZ7fgRXH7uxwKzFJT+V961R2hdIhiRbsxiIXdxqQlNJuQ/YfxlQC6IPTH4h+1ZFjPWaW+Wtp6Ja1GS5cdqqz8z8P+OuN6Iiv5A7+7Dod/gCu4r9jpn++GGhWgFe6lXvsK7KfPrdldB9jLnC2qVDgpXiXBOiAOWQ6cBSbtWZq3KNR4Luyyyn8hNB76QPE+6qtwf2S2WtJXLkjUJZsB0ruYqb7wV537d4jsDLiL4EUlz3IJoYc/QH+aJvSxC9Op1r4Z6y/kOLirmztjY9wwMHxFGYXSuweONM32XR+kuKt8dlgkgDpncotOQkCyJ7Qb71n2gb3fc=
  app: damp-journey-72310
  on:
    repo: peddilama/TicTacToe