language: java
before_install:
- chmod +x gradlew
deploy:
  provider: heroku
  api_key:
    secure: aRWcO21baiZMNWAqiwbjL6GQjM/8dCdtdbeJmzofKEI9BbJcMEzDzwB/VTIL7VMKT8a22VrKUI8/US7Pq1++o7VKJ0h6NArN8CS0DWuLpbG9Vk4fX8olfTa/UyJKeDPSC9LV3kZ25n0NWdJLQzW6eBwcRGtYjkD1s57fGQ6Y3QcboQem7ZRLtu37bkshHmo8eDTeis7ANDxTv0eEcFi42cM7p2s1XLYuN02EW4qfth+b+0S+trG4XF1pLk6xQDXp++F808zteuFxLDr6Fr/CMrgJ3QSMWUBm1qsAoX2x1bcIinlIsCpmnWy7VMi1OXEMir/tXuus0kBpzj1F88xaIydlenNyLj4ZpbBWXm9FwkKaXbN9QaJYatVM+kUCrFqQJSQC2io7ttwjAXMvY2231beSsVEYJ29ux7Ft9sg5l90hn5Y7z1HdZtJahwHUjOJAaFJJ/Sqh0vzaL/9hOQGQtu2j+Rcp18WOdbtaBaWJ+MBHo8IoQ13BvNXOtbEhrZSgb1wty8zDDu94j9RExtkk3HP1IptLR+COSaLm3o/Yxdyb3Qho19q8rSsUWAlgSAlGjjiPedNJCFZTwT2nm9cbdHLrDygb+6izXS+yTZJS8VJLz6xlppyD+VMEQgb62X4Xsgzdbz9/jHDVYGpZ9izb53oZEAxkXg+NnQKYAIpLwQ0=
  app: damp-journey-72310
  on:
    repo: peddilama/TicTacToe
